---
patching_repos:
  - name: Global Updates
    label: global
    baseurl: 'http://yum.box/all/'
    enabled: True
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7'
    gpgcheck: 1
  - name: Web Server Updates
    label: web
    baseurl: 'http://yum.box/web/'
    enabled: True
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7'
    gpgcheck: 1
